on: pull_request
name: Review
jobs:
  changelog:
    runs-on: ubuntu-latest
    name: Changelog should be updated
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Git fetch
        run: git fetch

      - name: Check that changelog has been updated.
        run: git diff --exit-code origin/${{ github.base_ref }} -- CHANGELOG.md && exit 1 || exit 0

  check-build-release:
    runs-on: ubuntu-latest
    name: Test create release
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create test release
        run: |
          docker compose build && docker run --user root --rm --volume ${PWD}:/app itkdev/php8.3-fpm:latest ./bin/create-release dev-test

  run-code-blocks-from-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      # https://github.com/actions/setup-go
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23.0'

      # https://github.com/mikkelricky/markdown-code-runner
      # We need to run as root in GitHub Actions, hence the `--substitutions` hack!
      - run: |
          go run github.com/mikkelricky/markdown-code-runner@latest run \
            --verbose --echo '👉 ' \
            --substitutions '"docker compose run ": "docker compose run --user root "' \
            dev-install code-analysis check-coding-standards prettier-check



      # prettier-check markdown-check shell-check composer-normalize
